Cleanup and minor refactoring to reduce inputs
Signed-off-by: David L. Armstrong <1403560+daversomethingsomething@users.noreply.github.com>

diff --git a/.github/workflows/conan-toolchain.yml b/.github/workflows/conan-toolchain.yml
--- a/.github/workflows/conan-toolchain.yml
+++ b/.github/workflows/conan-toolchain.yml
@@ -28,8 +28,6 @@ on:
         type: string
       save_cache_key:
         type: string
-      cache_package_paths:
-        type: string
       conan_home:
         type: string
       conan_local_recipes:
@@ -80,16 +78,32 @@ jobs:
       with:
         submodules: true
 
+    # We do this dynamically to reduce #inputs
+    # We can get away with this because we know how our deployer works here.
+    - name: Determine Cached Package Paths
+      id: determine_package_paths
+      run: |
+        if [[ "${{ inputs.conan_deployer }}" == "deb_deployer" ]]; then
+          echo "CACHE_PACKAGE_PATHS='*.deb'" >> $GITHUB_ENV
+        elsif [[ "${{ inputs.conan_deployer }}" == "rpm_deployer" ]]; then
+          echo "CACHE_PACKAGE_PATHS='RPM_HOME/rpmbuild/RPMS/*/*'" >> $GITHUB_ENV
+        else
+          echo "ERROR: Unsupported Conan Deployer: 'inputs.conan_deployer }}'"
+          exit 1
+        fi
+
     - name: Restore Deployed Packages from Cache
       if: ${{ inputs.restore_cache_key }}
       uses: actions/cache/restore@v4
       with:
         path: |
-          package_deploy/${{ inputs.cache_package_paths }}
+          package_deploy/${{ env.CACHE_PACKAGE_PATHS }}
         key: ${{ inputs.restore_cache_key }}
 
     - name: Install Cached RPM Packages
-      if: ${{ inputs.restore_cache_key && hashFiles('package_deploy/RPM_HOME/rpmbuild/RPMS/*/*') != '' }}
+      if: ${{ inputs.restore_cache_key
+       && inputs.conan_deployer == 'rpm_deployer'
+       && hashFiles('package_deploy/${{ env.CACHE_PACKAGE_PATHS }}') != '' }}
       run: |
         echo "Installing:"
         for package in package_deploy/RPM_HOME/rpmbuild/RPMS/*/*; do
@@ -101,13 +115,15 @@ jobs:
         while IFS= read -r line; do printf '    %s\n' "${line}"; done < $GITHUB_PATH
 
     - name: Install Cached .deb Packages
-      if: ${{ inputs.restore_cache_key && hashFiles('package_deploy/*.deb') != '' }}
+      if: ${{ inputs.restore_cache_key
+       && inputs.conan_deployer == 'deb_deployer'
+       && hashFiles('package_deploy/${{ env.CACHE_PACKAGE_PATHS }}') != '' }}
       run: |
         echo "Installing:"
-        for package in package_deploy/*.deb; do
+        for package in package_deploy/${{ env.CACHE_PACKAGE_PATHS }}; do
           printf '    %s\n' "${package}"
         done
-        dpkg --install package_deploy/*.deb
+        dpkg --install package_deploy/${{ env.CACHE_PACKAGE_PATHS }}
         echo "${{ inputs.toolchain_prefix }}/bin" >> $GITHUB_PATH
         echo "New GITHUB_PATH:"
         while IFS= read -r line; do printf '    %s\n' "${line}"; done < $GITHUB_PATH
@@ -194,11 +210,13 @@ jobs:
       uses: actions/cache/save@v4
       with:
         path: |
-          package_deploy/${{ inputs.cache_package_paths }}
+          package_deploy/${{ env.CACHE_PACKAGE_PATHS }}
         key: ${{ inputs.save_cache_key }}
 
     - name: Upload RPM Packages to Artifact Management
-      if: ${{ inputs.upload_packages && hashFiles('package_deploy/RPM_HOME/rpmbuild/RPMS/*/*') != '' }}
+      if: ${{ inputs.upload_packages
+       && inputs.conan_deployer == 'rpm_deployer'
+       && hashFiles('package_deploy/${{ env.CACHE_PACKAGE_PATHS }}') != '' }}
       shell: bash
       env:
         NEXUS_CI_PASSWORD: ${{ secrets.NEXUS_CI_PASSWORD }}
@@ -232,7 +250,9 @@ jobs:
         echo "Done."
 
     - name: Upload Debian Packages to Artifact Management
-      if: ${{ inputs.upload_packages && hashFiles('package_deploy/*.deb') != '' }}
+      if: ${{ inputs.upload_packages
+       && inputs.conan_deployer == 'deb_deployer'
+       && hashFiles('package_deploy/${{ env.CACHE_PACKAGE_PATHS }}') != '' }}
       shell: bash
       env:
         NEXUS_CI_PASSWORD: ${{ secrets.NEXUS_CI_PASSWORD }}
@@ -241,7 +261,7 @@ jobs:
         NEXUS_APT_REPO: ${{ vars.NEXUS_APT_REPO }}
       run: |
         echo "Uploading:"
-        for package in package_deploy/*.deb; do
+        for package in package_deploy/${CACHE_PACKAGE_PATHS}; do
           printf '    %s\n' "${package}"
 
           # Adapted from:
